const responseMessage = {
  SUCCESS: "Success",
  FAILURE: "Failure",
  NOT_FOUND: "Not Found",
   INTERNAL_SERVER_ERROR: "Internal Server Error",
   UNAUTHORIZED: "Unauthorized",
   FORBIDDEN: "Forbidden",
   BAD_REQUEST: "Bad Request",
   CONFLICT: "Conflict",
   UNPROCESSABLE_ENTITY: "Unprocessable Entity",
   TOO_MANY_REQUESTS: "Too Many Requests",
   SERVICE_UNAVAILABLE: "Service Unavailable",
   GATEWAY_TIMEOUT: "Gateway Timeout",
   HTTP_VERSION_NOT_SUPPORTED: "HTTP Version Not Supported",
   NETWORK_AUTHENTICATION_REQUIRED: "Network Authentication Required",
   PROXY_AUTHENTICATION_REQUIRED: "Proxy Authentication Required",
   REQUEST_TIMEOUT: "Request Timeout",
   REQUEST_URI_TOO_LONG: "Request URI Too Long",
   REQUESTED_RANGE_NOT_SATISFIABLE: "Requested Range Not Satisfiable",
   EXPECTATION_FAILED: "Expectation Failed",
   IM_A_TEAPOT: "I'm a teapot",
   MISDIRECTED_REQUEST: "Misdirected Request",
   UNEXPECTED_CONDITION: "Unexpected Condition",
   UPGRADE_REQUIRED: "Upgrade Required",
   PRECONDITION_REQUIRED: "Precondition Required",
   TOO_EARLY: "Too Early",
   REQUEST_HEADER_FIELDS_TOO_LARGE: "Request Header Fields Too Large",
   UNAVAILABLE_FOR_LEGAL_REASONS: "Unavailable For Legal Reasons",
   CLIENT_CLOSED_REQUEST: "Client Closed Request",
}
export default responseMessage